console.log (typeof 125)
console.log (typeof 'Veinticinco')
console.log (typeof -666)
console.log (typeof true)
console.log (typeof 0)
console.log (typeof '')
console.log (typeof null)
console.log (typeofundefined)
console.log (typeof FALSE)
